version: '3'

services:
  minio:
    image: minio/minio
    ports:
      - ":9000"
      - ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
    volumes:
      - ./minio:/data
    command: server /data --console-address ":9001"
    networks:
      - code-network
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    hostname: redis
    environment:
      REDIS_ARGS: "--requirepass password"
    logging:
      driver: 'json-file'
      options:
        max-size: '2m'
        max-file: '5'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
    networks:
      - code-network
    ports:
      - :6379
  chromadb:
    image: ghcr.io/chroma-core/chroma:0.5.23
    container_name: chromadb
    volumes:
      - ./chroma:/chroma/chroma/  # Persist data to a volume
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_PORT=8000
      - ALLOW_RESET=TRUE
    networks:
      - code-network
    ports:
      - :8000
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: iank
      POSTGRES_DB: mydb
    ports:
      - :5432
    volumes:
      - ./mydb:/var/lib/postgresql/data
    networks:
      - code-network
  app:
    image: ghcr.io/sofyan48/ochabot/ochabot
    ports:
      - 8081:8081
    networks:
      - code-network
    restart: always
    command: "python main.py serve"
    volumes:
      - ./.env:/app/.env
      - ./storage:/app/storage

  migrate:
    image: ghcr.io/sofyan48/ochabot/ochabot
    networks:
      - code-network
    restart: on-failure:3
    command: "alembic upgrade head"
    volumes:
      - ./.env:/app/.env
networks:
  code-network:
    driver: bridge